### ISSUE TITLE
Android Drawer Support?

### ISSUE THREAD

**Issue by lylepratt** [Telerik-Verified-Plugins/NativePageTransitions#10]
Are you guys planning on releasing support for the Drawer on Android? I found this while researching alternatives to AppGyver (which has native Android Drawer) and was disappointed to see that it was missing.

**Comment by ecerroni** [comment]
May you elaborate more on "you can always bind something like hammer.js"

Actually I'm looking on trying to do this with touchswipe.js.

Where I should tap in your code?

Thanks.
