### ISSUE TITLE
Header flickers slightlly when sliding left with duration < 400ms

### ISSUE THREAD

**Issue by genixpro** [Telerik-Verified-Plugins/NativePageTransitions#101]
On my phone, a Nexus 5, I see a small flicker in the fixed header element when using the slide-left transition with a 300ms duration. Its as if the fixed header element is being removed 1 frame too soon, when the webview animation isn't totally completed sliding in. This results in a slight flicker as the header appears to shift right by one or two pixels, and then back to the regular position.

I have prepared a pull request which seems to resolve the issue: https://github.com/Telerik-Verified-Plugins/NativePageTransitions/pull/100

The two animation objects, one for the web view and one for the screenshot image, don't appear to be perfectly synchronized. Simply by changing the event to get triggered when the webview finished animating, instead of when the image finishes animating, I was able to resolve the issue.

**Comment by EddyVerbruggen** [comment]
Closed via #101
