### ISSUE TITLE
Error: Missing Command Entry

### ISSUE THREAD

**Issue by stefanoavancini** [Telerik-Verified-Plugins/NativePageTransitions#102]
Hello, I have a problem with Windows Phone platform on phonegap (In andriod and iOS all works perfectly). I try to execute this code:

function slide(direction, color, slowdownfactor, hrf) {
    if (!hrf) {
        setTimeout(function () {
            // update the page inside this timeout
            //document.querySelector("#title").innerHTML = direction;
            //document.querySelector("html").style.background = color;
        }, 20);
    }
    // not passing in options makes the plugin fall back to the defaults defined in the JS API
    var theOptions = {
        "direction": "right", // 'left|right|up|down', default 'left' (which is like 'next')
        "duration": 500, // in milliseconds (ms), default 400
        "slowdownfactor": 3, // overlap views (higher number is more) or no overlap (1), default 4
        "iosdelay": 100, // ms to wait for the iOS webview to update before animation kicks in, default 60
        "href": hrf,
        "androiddelay": 150, // same as above but for Android, default 70
        "winphonedelay": 250, // same as above but for Windows Phone, default 200,
        "fixedPixelsTop": 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
        "fixedPixelsBottom": 0  // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
    };
    window.plugins.nativepagetransitions.slide(
        theOptions,
        function () {
            console.log('------------------- slide transition finished');
        },
        function (msg) {
            console.log('error: ' + msg);
        });

And than I try to call slide function on click button like this:

<code>
slide('right', 'purple', 0, "index.html");
</code>

But when I click the button the page transition doesn't start and print an error:
error: Missing Command Error.
The device is a Microsoft Lumia 435.
Thank you

**Comment by EddyVerbruggen** [comment]
Hi, I'm not sure what causes this as I don't have a Windows device at the moment. The thing that seems odd is you're navigating to `index.html` while you are probably already there. Have you tried other pages and/or #views ?

**Comment by stefanoavancini** [comment]
I put this code in another page, not in index.html and I call the slide function on click button.

**Comment by EddyVerbruggen** [comment]
That error seems rather generic, not really plugin specific. Google kinda confirms this, can you please check a few of the suggestions? https://www.google.nl/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=cordova+windows+phone+%22Missing+Command+Error%22&es_th=1
