### ISSUE TITLE
Call back not called on IOS 9

### ISSUE THREAD

**Issue by northkode** [Telerik-Verified-Plugins/NativePageTransitions#104]
Not sure if this is only on IOS 9 and WkWebView or if its an IOS in general issue.. but i definitely can't get my callbacks to fire for animation or pendinganimation

**Comment by EddyVerbruggen** [comment]
Hi, which plugin version do you use? I fixed a similar issue with 0.5.6.

**Comment by northkode** [comment]
I just used the cordova plugin add from the repo.. i would assume that master is the latest? no?

**Comment by EddyVerbruggen** [comment]
Yes it is, so it must be a different problem - what exact code are you using to get this problem?

**Comment by northkode** [comment]
Whats odd is i installed this a few days ago.. but i just checked the plugin version and i had 0.5.5.. so i just removed it and reinstalled and now its 0.5.6, and it seems to work now. 
Thanks for the heads up!

**Comment by EddyVerbruggen** [comment]
Ha, nice. Closing :+1:
