### ISSUE TITLE
Target page visible during flip transition on iOS

### ISSUE THREAD

**Issue by midasdas** [Telerik-Verified-Plugins/NativePageTransitions#107]
Hello

Thanks for the great plugin. However, I'm not able to implement it in my app yet, because of this issue that looks like a bug.

I have created a basic Cordova/PhoneGap project with a two page layout using CSS and anchors. I'm using two div's with 100% height and scrolling disabled on the html tag. I'm not using any framework for handling the page layout, I'm only using jQuery Mobile for touch events.

The flip transition from page 1 to page 2 works, but the page being transitioned to is already visible when the animation kicks in. This happens on iOS only, on Android it works fine.

I have attached the Cordova project for the test app that I wrote:
[myApp.zip](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/files/83219/myApp.zip)

Thanks!

Midas

**Comment by EddyVerbruggen** [comment]
Hi, thanks for the example. I was able to fix it by setting the `iosdelay` to `0` (it's not `0` by default):

In `index.html`:
```js
// stuff here
'duration'  : 1000, // you already have this
'iosdelay'  : 0 // the new property
```

Nice swipe-flip effect btw, I love it!
