### ISSUE TITLE
fade transition fades in from white only on iOS hardware

### ISSUE THREAD

**Issue by mccraigmccraig** [Telerik-Verified-Plugins/NativePageTransitions#109]
fade transition appears to work fine on android emulator and hardware, and on iOS simulator

but on real iOS hardware it fades in from white rather than from a screenshot

**Comment by EddyVerbruggen** [comment]
Can you share a sample so I can quickly reproduce that?

**Comment by mccraigmccraig** [comment]
i'll put a test repo together on monday :c

**Comment by mccraigmccraig** [comment]
not quite monday, but as close as i could manage :)

https://bitbucket.org/employeerepublic/cordova-test-fade

the sample has slide and fade transitions - slide works fine on iOS emulator and hardware, but fade works properly on emulator and flashes to white before fading in on hardware

the repo has everything apart from my `platforms` directory... it'll take a long time to upload that on my home DSL, so hopefully you won't need it

**Comment by EddyVerbruggen** [comment]
Hi, so that [www folder](https://bitbucket.org/employeerepublic/cordova-test-fade/src/a385da6a0937f497a5814c43e0ee32763fda5bb4/www?fileviewer=file-view-default) links to a non existinc folder and I have no idea how to generate it. Can you take a look? It would be easiest if you can zip up the platforms/ios folder and share that zip with me. Then it'll just work.

Thanks for the efforts!

**Comment by mccraigmccraig** [comment]
oops - sorry. i didn't look at the lower-level .gitignores

i've added the missing generated folders, and a .tgz ios platforms folder

**Comment by EddyVerbruggen** [comment]
@mccraigmccraig Unzipping that iOS.tgz works fine and on the simulator the fades look sweet.

Deploying on a device however leaves met looking at the spinner and splashsscreen, with this error in the console:

```
2016-01-29 11:17:20.816 test-fade[452:132142] [PW] [I] -[PWRequestManager] 
x
|    Pushwoosh request:
| Url:      https://cp.pushwoosh.com/json/1.3/registerUser
| Payload:  {"request":{"device_type":1,"application":"","userId":"4CA0E2B0-542D-4F37-9769-749E43B0F9F1","v":"3.0.13.443","hwid":"4CA0E2B0-542D-4F37-9769-749E43B0F9F1"}}
| Status:   "200 no error"
| Response: {"status_code": 210, "status_message": "Request format is not valid."}
x
2016-01-29 11:17:20.817 test-fade[452:132144] [PW] [I] -[PushNotificationManager] sending appOpen failed
```

Since the app is minified I can't get past this..

**Comment by mccraigmccraig** [comment]
darn, i'll strip out some more plugins and recompile


On 29 January 2016 at 10:22:53, Eddy Verbruggen (notifications@github.com) wrote:

@mccraigmccraig Unzipping that iOS.tgz works fine and on the simulator the fades look sweet.

Deploying on a device however leaves met looking at the spinner and splashsscreen, with this error in the console:

2016-01-29 11:17:20.816 test-fade[452:132142] [PW] [I] -[PWRequestManager]  
x
|    Pushwoosh request:
| Url:      https://cp.pushwoosh.com/json/1.3/registerUser
| Payload:  {"request":{"device_type":1,"application":"","userId":"4CA0E2B0-542D-4F37-9769-749E43B0F9F1","v":"3.0.13.443","hwid":"4CA0E2B0-542D-4F37-9769-749E43B0F9F1"}}
| Status:   "200 no error"
| Response: {"status_code": 210, "status_message": "Request format is not valid."}
x
2016-01-29 11:17:20.817 test-fade[452:132144] [PW] [I] -[PushNotificationManager] sending appOpen failed

Since the app is minified I can't get past this..

**Comment by mccraigmccraig** [comment]
ok, i've removed the pushwoosh plugin, so that shouldn't happen anymore - hopefully should be good now

**Comment by EddyVerbruggen** [comment]
Can you push those changes (incl the ios zip)? Cheers.

**Comment by mccraigmccraig** [comment]
oops. sorry - i'm not much good at predicting what needs pushing yet

i've pushed a new ios zip

**Comment by EddyVerbruggen** [comment]
Thanks. Did you try that folder? I needed to disable wkwebview plugin to get it running on my phone. Then slide works fine an fade doesn't work at all.

Rather than going through this cycle a few additional times I'd like you to [grab this www folder](https://dl.dropboxusercontent.com/u/10061342/transitions-www.zip) and copy it inside your platforms/ios/www folder.

I'm curious to learn if the fade in there works correctly..

**Comment by mccraigmccraig** [comment]
ok, getting somewhere now

i've tried your www folder and it worked on both emulator and hardware - which lead me to modify my code to use delayed rather than pending transitions, and delayed fade transitions also work fine for me on the hardware

so it's just the *pending* fade transitions on the hardware that are problematic. i've updated my sample to include both pending and delayed transitions - i couldn't get pending to work properly on your www folder for some reason

i've created a new cordova project (same git url) and added just nativepagetransitions and wkwebview plugins and ios platform (since it seems most of the above problems were caused by me re-purposing another cordova project and trying unsuccessfully to strip stuff out)

wrt wkwebview - for me pending fade behaves a bit better with wkwebview  - without wkwebview plugin the pending fade transition doesn't seem to work at all - it just abruptly changes to the new view - with wkwebview it flashes to white then fades in

**Comment by mccraigmccraig** [comment]
i did some more playing and figured out my problem was WkWebView related - the screenshot was turning out pure white, hence the "fade in from white" behaviour

some code inspection lead to the above fix, which just copies the slide transition method for taking a screenshot, which work with WkWebView
