### ISSUE TITLE
Header/Footer frozen

### ISSUE THREAD

**Issue by zwand19** [Telerik-Verified-Plugins/NativePageTransitions#110]
Every once in a long while the fixedPixels do not go away after a transition is complete. They are stuck over the page, when I click on them it interacts with the content behind them but they never go away until the app is restarted. Can't seem to figure out why this is happening

This is on iOS using a delay of -1.

calling window.plugins.nativepagetransitions.executePendingTransition() again has no effect

Has anyone else encountered this?

**Comment by EddyVerbruggen** [comment]
Do you perhaps have some app that reproduces this issue?

**Comment by zwand19** [comment]
No I don't =/  Can't figure out what causes it. Happens very infrequently.

**Comment by EddyVerbruggen** [comment]
Perhaps it's because the animation completion handler doesn't fire for some reason - I've now implemented removing those headers and footers differently. Available from the master branch (the default) of this Github repo.

**Comment by zwand19** [comment]
Thanks!
