### ISSUE TITLE
window.plugins.nativepagetransitions error in provider.js

### ISSUE THREAD

**Issue by prakash-alpine** [Telerik-Verified-Plugins/NativePageTransitions#111]
I installed this plugin but can't get it to work. Upon debugging in Firebug console I got to following code

```
	    /**
	     * @ngdoc function
	     * @name ionic-native-transitions.$ionicNativeTransitionsProvider#isEnabled
	     * @access public
	     * @methodOf ionic-native-transitions.$ionicNativeTransitionsProvider
	     *
	     * @description
	     * Is ionic-native-transitions enabled or not?
	     */
	    /**
	     * @ngdoc function
	     * @name ionic-native-transitions.$ionicNativeTransitions#isEnabled
	     * @access public
	     * @methodOf ionic-native-transitions.$ionicNativeTransitions
	     *
	     * @description
	     * Is ionic-native-transitions enabled or not?
	     */
	    function isEnabled() {
	        if (window.cordova && window.plugins && **window.plugins.nativepagetransitions**) {
	            return enable;
	        }
	        return false;
	    }
```

The 'window.plugins.nativepagetransitions' is not enabled so it returns false and page transitions do not occur.  My questions:

1.  Do I need to install  telerik's native-page-transitions plugin. (http://plugins.telerik.com/cordova/plugin/native-page-transitions) for this to work? 
2. Do I need to install both native-page-transitions and ionic-native-transitions plugins to make work?
3.  Should I expect this to work in the browser with "ionic serve" command. 
4.  If not, can I see test the transitions in "ionic view" app on device?
5.  if not, do I have to build and deploy native application to see the transitions?

Sorry for asking so many questions. I am new to Ionic development and there is overlapping and often confusing information on internet about native-page-transitions and ionic-native-transitions.

**Comment by EddyVerbruggen** [comment]
1. yes
2. yes
3. no
4. no
5. yes

**Comment by prakash-alpine** [comment]
Thanks your for prompt reply. It will be good if this information is included on the github page. it will help many newcomers like me.

**Comment by EddyVerbruggen** [comment]
I appreciate your suggestion, but it's more of a common Cordova / Ionic thing really. Not related to any specific plugin.
