### ISSUE TITLE
[iOS] WKWebView Engine - fixedPixelsTop permanently adds top margin to body

### ISSUE THREAD

**Issue by roblav96** [Telerik-Verified-Plugins/NativePageTransitions#112]
Tried using this plugin today on ios with WKWebView Engine.

When I tried to use fixedPixelsTop  with the slide transition (left and right) it permanently added a top margin to the body of my app. And when I say 'permanently' even after browser refresh, it's still there. I had to force kill the app and recompile to get it back to normal.

Screenshot:
![img_0004](https://cloud.githubusercontent.com/assets/1457327/12767296/5bb0b7d2-c9d6-11e5-9d7e-16ef7dc2fec5.png)

**Comment by EddyVerbruggen** [comment]
Just for my peace of mind: are you implicitly saying that it works fine without wkwebview?

**Comment by EddyVerbruggen** [comment]
I was able to reproduce and fix it, can you try again from the master branch please?

(note to self: UIWebView was fine)

**Comment by roblav96** [comment]
I have **not** tested using UIWebView. I'm sure it works fine though.

**Comment by EddyVerbruggen** [comment]
Closing this (and releasing it)
