### ISSUE TITLE
Need to disable companion app warning

### ISSUE THREAD

**Issue by jamielob** [Telerik-Verified-Plugins/NativePageTransitions#115]
Hi!

First off, thank you for creating and maintaining such an amazing plugin. 

I'm using the plugin as part of other frameworks successfully but keep getting the logged warning message:
"Probably running inside a companion app, your app may crash if your html file is not in the root!"

Is there any chance you can add a option/setting that I can use in production to hide that? 

Thanks!

Jamie

**Comment by EddyVerbruggen** [comment]
Hi, yeah I've removed it because there's a (working) fallback anyway.

Thanks,
Eddy

**Comment by jamielob** [comment]
Thank you!
