### ISSUE TITLE
[FEATURE] cancelPendingTransition()

### ISSUE THREAD

**Issue by roblav96** [Telerik-Verified-Plugins/NativePageTransitions#123]
Sometime's I would need to cancel a pending transition and when I call executePendingTransition() well, it does exactly that. lol

Would it be possible to add a cancelPendingTransition() method so a transition does not appear at all so the user can continue to interact with the page? Maybe a disappearPendingTransition() method?

**Comment by EddyVerbruggen** [comment]
Hi, the problem is that when invoking fi. `slide` it will create a screenshot of your current page (state A) and overlay that on the webview (hiding the webview). While that is showing the webview will load the href you passed in so its state will update (state B).

Implementing a `cancelPendingTransition` function would only mean we'll just remove the screenshot without a transition, but that would look a bit strange right? As it would switch from state A to B in 1 frame.

Thoughts?

**Comment by roblav96** [comment]
It's no worries!

Here's an example in case you are wondering. I'm using vue.js with vue-router. Before every state change, I call nativepagetransitions(). In some routes, I have a canDeactivate hook which gets called **after** I call nativepagetransitions(). During this canDeactivate hook I call executePendingTransition() because if I do not, then the screenshot stays on the user's screen. For now I've reworked how and when my hooks get called, but I thought it would be nice if a cancelPendingTransition() method would just make the current screenshot completely disappear instead of doing the transition, then disappearing.

**Comment by EddyVerbruggen** [comment]
Yes that would be possible - so to be sure the webview actually doesn't change its view contents in your case (canDeactive), right? Then it would make sense to me as well.

**Comment by roblav96** [comment]
Yes, that's correct. I never change the contents of the webview after calling nativepagetransitions()

**Comment by roblav96** [comment]
I'll give it a shot. Eating food :pizza:

**Comment by roblav96** [comment]
# CONFIRMED
Works great on **Android** and **iOS**

**Comment by EddyVerbruggen** [comment]
Awesome, thx for the quick test - I'll tag a new version soon.

**Comment by roblav96** [comment]
Thanks so much man! Huge help. You're certainly getting a banner in my project.

**Comment by aacassandra** [comment]
Hi @roblav96 , can you give a little example of how to use the native page transition in ionic / vue. i have trouble finding documentation for this. Thank you in advance
