### ISSUE TITLE
See previous screen while next state transiton

### ISSUE THREAD

**Issue by svsool** [Telerik-Verified-Plugins/NativePageTransitions#124]
iPad-Mini 8.4
wkwebview 0.6.9
com.telerik.plugins.nativepagetransitions 0.6.3

https://vimeo.com/158166742 - bug when slide to page which contains tabs
https://vimeo.com/158171241 - bug when use flip transition between tabs

my settings:
```javascript
  $ionicNativeTransitionsProvider.setDefaultOptions({
    triggerTransitionEvent: '$ionicView.afterEnter',
    backInOppositeDirection: false,
  });
```

This happens only when I try to go to page that contain ion-tabs. I noticed if set iosdelay 1000 for transitions to pages that contains tabs, all is ok. When I disable wkwebview plugin and use old webview, all work even without iosdelay. I can share chunk of my app if needed. This bug absent in iOS simulator, only on device.

**Comment by p1ng** [comment]
hi @svsool, I noticed you closed this issue but I didn't see a commit that fixed it.  Would you mind sharing how you resolved this?

**Comment by hossam9995** [comment]
+!

**Comment by svsool** [comment]
#77
