### ISSUE TITLE
[IOS] UIWebView. fixedPixelsTop permanently adds top margin to body

### ISSUE THREAD

**Issue by z1key** [Telerik-Verified-Plugins/NativePageTransitions#126]
The problem is same as in #112
I no using CrossWalk because phonegap version doesnot support it.
Build Phonegap v.3.7.0

The pluginlist which I using:
com.ionic.keyboard   	                                pgb	1.0.3	n/a	1.0.3	android,ios
com.oauthio.plugins.oauthio                    	pgb	0.2.4	n/a	0.2.4	android,ios,winphone
com.telerik.plugins.nativepagetransitions   	npm	*	n/a	n/a	android,ios,winphone
cordova-plugin-datepicker   	                        npm	*	n/a	n/a	android,ios,winphone
cordova-plugin-dialogs          	pgb	1.1.1	n/a	1.1.1	android,ios,winphone
cordova-plugin-globalization   	pgb	1.0.1	n/a	1.0.1	android,ios,winphone
cordova-plugin-inappbrowser   	npm	*	n/a	n/a	android,ios,winphone
cordova-plugin-network-information   	pgb	1.0.1	n/a	1.0.1	android,ios,winphone
cordova.plugins.diagnostic.api-22   	npm	*	n/a	n/a	android,ios,winphone
net.yoik.cordova.plugins.screenorientation   	pgb	1.3.1	n/a	1.3.1	android,ios
org.apache.cordova.device   	pgb	0.3.0	n/a	0.3.0	android,ios,winphone
org.apache.cordova.geolocation   	pgb	0.3.12	n/a	0.3.12	android,ios,winphone
org.apache.cordova.home   	npm	*	n/a	n/a	android,ios,winphone
org.apache.cordova.statusbar   	pgb	0.1.4	n/a	0.1.4	android,ios,winphone

**Comment by EddyVerbruggen** [comment]
Please show your code.

**Comment by z1key** [comment]
`function nextAnim() {
    var navbar_height = $('.main_nav').height();
    if (typeof window.plugins !== 'undefined') {
        window.plugins.nativepagetransitions.slide({
            "direction": "left", // 'left|right|up|down', default 'left' (which is like 'next')
            "duration": 300,
            "iosdelay": 100,
            "androiddelay": 200,
            "fixedPixelsTop": navbar_height
        });
    }
}`

**Comment by EddyVerbruggen** [comment]
And that's on iOS with UIWebView on a real device, right?

**Comment by z1key** [comment]
Yes it is on iPhone 5

**Comment by EddyVerbruggen** [comment]
And can I have that project perhaps?

**Comment by z1key** [comment]
Which part of code is interesting to you?

**Comment by EddyVerbruggen** [comment]
If you want the quickest possible solution a simple app reproducing the issue works best. So anything reproducing it really.

**Comment by z1key** [comment]
![screen1](http://cs633122.vk.me/v633122375/1b405/A0a2Rlvm0es.jpg)
![screen2](http://cs633122.vk.me/v633122375/1b404/jYfGCFAeLq0.jpg)

**Comment by z1key** [comment]
The black bar is flashing for miliseconds while screen changing animation finshed

**Comment by EddyVerbruggen** [comment]
That's not supposed to happen - let me dive into this today.

**Comment by z1key** [comment]
Thank you for your understanding and responsiveness . I would hope for a decision

**Comment by EddyVerbruggen** [comment]
As a quick fix I think you'll have better results with version 0.6.1. Can you pin to that for now?

**Comment by z1key** [comment]
<gap:plugin name="com.telerik.plugins.nativepagetransitions" spec="0.6.1" source="npm" />

Error - Plugin (or a specific plugin version) not found in external repo: com.telerik.plugins.nativepagetransitions@0.6.1": Fetching plugin "com.telerik.plugins.nativepagetransitions@0.6.1" via npm Failed to fetch plugin

**Comment by EddyVerbruggen** [comment]
My bad, try 0.6.0:

<img width="663" alt="screen shot 2016-03-10 at 15 15 44" src="https://cloud.githubusercontent.com/assets/1426370/13671943/fdec5790-e6d2-11e5-9d9f-d77c4a8bf478.png">

**Comment by z1key** [comment]
I tried 0.6.0 version and had seen that 
![scr]http://cs633122.vk.me/v633122375/1b5c9/p3KWIFpxlyk.jpg
It happened because I used Statusbar plugin? How can I fix that?

**Comment by z1key** [comment]
Now the best solution for me is
Plugin version 0.6.0
`navbar_height = (isIos)? screen.height - document.height + $('.main_nav').height(): $('.main_nav').height();`

**Comment by EddyVerbruggen** [comment]
Can you try the latest from github please? I understood that you can now load plugins directly from GitHub with phonegap build, so that should be possible.

**Comment by z1key** [comment]
Sory but it's not posibly now. I can load only with npm.

**Comment by EddyVerbruggen** [comment]
@z1key How do you build your app?

**Comment by z1key** [comment]
with phonegap build

**Comment by EddyVerbruggen** [comment]
What did you try and why doesn't it work? Please [check this blog](http://phonegap.com/blog/2016/02/16/git-plugins/) and if it doesn't work we need to file a bugreport with them.

**Comment by z1key** [comment]
Sory I was no right. Plugin added fine. Testing...
