### ISSUE TITLE
Views sometimes not switching correctly on iOS

### ISSUE THREAD

**Issue by Lefystore** [Telerik-Verified-Plugins/NativePageTransitions#128]
Hi, I'm trying to switch views by showing/hiding them using jQuery, this is what I have so far:

```
var options = {
	  "direction"      : effect, //left, right or whatever
	  "duration"	   : 230,
	  "iosdelay"       :  75,
	  "androiddelay"   :  75
	};


	setTimeout(function() {
           $(show).show();
	}, 70);

		window.plugins.nativepagetransitions.slide(
	        options,
	        function (msg) {
	            $(hide).hide();
	           
	        }, // called when the animation has finished
	        function (msg) {
	            $(hide).hide();
	            
	        } // called in case you pass in weird values
});
```

The problem is, in some cases, the view isn't updated before the transition kicks in so, what you see is the same page sliding in and out, and after the transition is done, it changes to the correct page.

I tried without the setTimeout function, also tried setting iosdelay to 0, 10, 50, 100, or any other number without any difference.
This only happens on iOS by the way, on android, it works like a charm.

I tried calculating the time lapse between page changes.. and found out that the times the transition fails, the page took 0 ms to switch views, the times the page takes 5 ms or more the transition works fine.. that is why I added the setTimeout function

**Comment by EddyVerbruggen** [comment]
Can't you send the new href to the plugin instead of using the timeout?

And ideally if you have an event on the new page where you can hook into when that page has loaded, then you can set iosdelay = -1 and call `executePendingTransition` when that even fires.

**Comment by Lefystore** [comment]
I tried using the `href` also but nothing changed. I particularly don't need to use the `executePendingTransition` since I just make a simple show/hide action, if I need to load something I would make it before or after the transition plugin is even called. The weird thing is that on some pages the transition works fine, but in some other it doesn't. Also I have no problems on Android devices at all. Its like on iOS the screenshot is taken before I display the new view. By the way this plugin is amazing and a must have for my projects. Thank you

**Comment by EddyVerbruggen** [comment]
If you're using the latest version (try the one here on github) and see this issue then I have no clue and am not currently in the position to debug your app myself.

**Comment by Lefystore** [comment]
Ok, thank you, I'll keep trying different combinations and I'll update this post if I find the solution.

**Comment by Lefystore** [comment]
Ok, I think solved it, what I did was:

```
var options = {
	  "direction"      : effect,
	  "iosdelay"       :  75,
	  "androiddelay"   :  75
	};

		setTimeout(function() {
		    $(show).show();
		    $(hide).hide();
		}, 70);

		window.plugins.nativepagetransitions.slide(
	        options,
	        function (msg) {
	        }, // called when the animation has finished
	        function (msg) {
	        } // called in case you pass in weird values
	    );
```

The problem was that I was hiding the old view after the transition was complete, now I hide it after the 70 ms but before the transition kicks in, so I give the plugin time to take the screenshot.

Thanks
