### ISSUE TITLE
Jumping 2 States Back

### ISSUE THREAD

**Issue by fmoessle** [Telerik-Verified-Plugins/NativePageTransitions#129]
I have structured my ionic-app like this (and it works fine without the plugin and the adapter):

state x: url=x
state y: url=x/y
state z: url=x/y/z

When clicking the "InAppBackButton" in state z, It throws me into state x instead of y.

Tested with Crosswalk 15,16,17 and no Crosswalk at all.

On the other hand the "HardwareBackButton" works perfectly, but without an animation.

**Comment by EddyVerbruggen** [comment]
Are you using the adapter that's part of this repo (it's a bit old, possibly outdated), or this popular one: https://github.com/shprink/ionic-native-transitions

**Comment by fmoessle** [comment]
I got it from this repo

**Comment by fmoessle** [comment]
I will try one of those https://github.com/shprink/ionic-native-transitions/tree/develop/dist

**Comment by fmoessle** [comment]
That's it. Works fine.

I really appreciate your work (i'm also using the custom url scheme plugin ;) )

**Comment by EddyVerbruggen** [comment]
Sweet!
