### ISSUE TITLE
[iOS] Fade Animation doesn't work anymore. Slide animations works incorrect

### ISSUE THREAD

**Issue by z1key** [Telerik-Verified-Plugins/NativePageTransitions#130]
Hello. Today I have seen some bugs on iOS.
1) Fade animation doesn't work with any options;
2) Slide animation work incorrectly. The first pages are changed instantly and then starts animation. It's look like a double changing. I tried with delay 0 and higher.
3) When I set delay  to -1 for the SLIDE  - animation does'nt show;
4) When I set delay  to -1 for the FADE - IT'S FREEZING my App. 
Testing on iPhone 5 native UIWebView.
Please answer ASAP

**Comment by EddyVerbruggen** [comment]
I hope this is ASAP enough for you.

Please share your project otherwise it's impossible to help you. Best would be the platforms/ios folder entirely so we can easily reproduce it.

**Comment by z1key** [comment]
I build with Phonegap build. Unable to get platform folder from the app. I add this to config.xml
`<plugin spec="https://github.com/Telerik-Verified-Plugins/NativePageTransitions.git" source="git" />`
There is my JS code to start animation:
`doc.on('touchend', '#btn_login_socials', function () {`
`showFadeAnim();`
`$page_container.html('');`
Where showFadeAnim() is : 
`if (typeof window.plugins !== 'undefined') {`
`window.plugins.nativepagetransitions.fade({`
`"duration"         :  200,`
`"iosdelay"         :  300,`
`"androiddelay"     :  50`
`});`
`}`
On Android all works fine.

**Comment by z1key** [comment]
I think it's happens after added new feature? because before update animation worked fine

**Comment by EddyVerbruggen** [comment]
Can you send me a small app reproducing it? Otherwise it will take long for me to get to it.

**Comment by z1key** [comment]
can you tell me your skype?

**Comment by EddyVerbruggen** [comment]
No but you can email me at eddyverbruggen at gmail dot com

**Comment by z1key** [comment]
Ok. One moment please.

**Comment by z1key** [comment]
I have sent to  you email with link

**Comment by z1key** [comment]
I sent a code via email. I don't have sources any more.

**Comment by EddyVerbruggen** [comment]
We're dealing with this by email. Note that the `-1` freezes are because that's because the manual transition mode is activated by that setting. It's all in the docs.
