### ISSUE TITLE
['NativePageTransitions'] took '13.155273' ms. Plugin should use a background thread

### ISSUE THREAD

**Issue by addi90** [Telerik-Verified-Plugins/NativePageTransitions#132]
I am getting this error while transtioning in my app in XCode. I think we need to make the transition to use a background thread for performance reasons

**Comment by addi90** [comment]
Any information on this yet

**Comment by EddyVerbruggen** [comment]
You can ignore this. This plugin needs to run on the UI thread since it's doing UI stuff. That's not allowed from a background thread.

**Comment by addi90** [comment]
@EddyVerbruggen  Thanks a lot for the response
