### ISSUE TITLE
feature: prepare next drawing / preload next context

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [Telerik-Verified-Plugins/NativePageTransitions#133]
I found this repo to be quite useful, unfortunately though it's a tick short to have pleasant drawer menu experience compared to native.
Would it be in scope of this repo to provide `.drawer.prepare(options)`, `drawer.execute(cb1, cb2)` methods and to somehow prepare the next context? Preserving the old context would help also. Is there someone that could implement those without a lot of pain? I could give it a shot, but have no real experience in Obj-C and Java.

@kibotu can you help out for the Java part? Should be a very small thing for you.

**Comment by eljefedelrodeodeljefe** [comment]
This would be reference doc (see drawer section) http://plugins.telerik.com/cordova/plugin/native-page-transitions

**Comment by kibotu** [comment]
i can look into it at the weekend i think

**Comment by eljefedelrodeodeljefe** [comment]
That would be uber-awesome. Thx.

**Comment by kibotu** [comment]
As far as I can see the lib doesn't use the [DrawerLayout](http://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html) so there wouldn't be a drawer.prepare to the begin with, instead it appears views are animated by themselves. At any rate, here are the drawer related actions: https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/src/android/NativePageTransitions.java#L212-L268. As for the context i'm not quiet sure what you need exactly. Is your current context unavailable at some point or something?

**Comment by eljefedelrodeodeljefe** [comment]
I was assuming so. It's gonna be a too big of change then. 

Thing is: you are triggerung the drawer animation and put a href property of a path to an .html file. That said .html file will be screenshoted immediately and then be animated. However when you use (slow) javascript in there then it is likely the your page hasn't been initialized yet and the page looks faulty. 

If there is no quick way of preloading it, I think this needs to be closed an I have to implement the drawer in css/js/html.

**Comment by eljefedelrodeodeljefe** [comment]
Closing. Probably no action item. Thx.
