### ISSUE TITLE
Android: UI Thread is sometimes blocked for several seconds

### ISSUE THREAD

**Issue by lookitsatravis** [Telerik-Verified-Plugins/NativePageTransitions#148]
Hello! Thanks for all of your work on this project. I've run into an issue which is difficult to reproduce, but is problematic for the app ux. I am using https://github.com/shprink/ionic-native-transitions which, more or less, disables the built-in ionic transitions and uses this library instead.

The way I ran into this issue is through a feature request that the app show a loading spinner if a transition is taking too long. So, I set up a timeout for 400ms that will show the spinner if the transition hasn't completed in that time frame. I know that this plugin uses the UI Thread, and that while it is working, the thread is blocked. So that 400ms timeout isn't constant, which is okay. It's close 90% of the time. Approximately 1 in 10 times, the UI is blocked for between 2 and 4 seconds by this plugin while it is performing its work.

I believe that executing in the UI thread is required, so I cannot modify the plugin to execute in another thread, but I am looking for any suggestions or pointers to make sure that the UI thread is not blocked for that long. Thanks!

**Comment by EddyVerbruggen** [comment]
Hi!

The thing is, the screenshot of the old page is being shown _until_ the transition executes. You're best off loading heavy content _after_ the transition finishes. Assuming your app is not always doing that as it is slow 1 in 10 times (network traffic?).

**Comment by lookitsatravis** [comment]
Hey @EddyVerbruggen - I hear you. I thought the same thing and took steps to correct when data was loading (after transitions), etc. But, there are views that don't fit this scenario. The Ionic wrapper for this library has support for clicking the "back" button which will go through Ionic's history stack and find the already cached view and display it. In that scenario, no data is loading (so it can't be network traffic), and even the HTML is already rendered, but the UI blocking still happens in this scenario which allowed me to rule out network traffic.

I narrowed it down to this plugin by using `console.time()` before the transition starts, and then again after it is completed, I also added a `console.log` in a setInterval that is fired every 50ms starting just before the transition is executed. Approximately 10% of the time, the setInterval is blocked for 2-4 seconds until the plugin success callback is fired.

Apologies for not having more specific info at this time, I cannot accurately reproduce it and only just last evening was able to narrow it down to the UI blocking. At this point, I'm looking for assistance in troubleshooting. I am happy to provide as much information as I can, but I'm not totally sure what to look for on the Java side or what tools are best for profiling this type of behavior.

**Comment by EddyVerbruggen** [comment]
Roger that.

Which Android devices (hardware/software) do you see this one and are there devices that don't show this problem?

I'm happy to try and reproduce it but it may be a bit specific to your app so if you want me to debug it I'd need your platforms/android folder.

**Comment by lookitsatravis** [comment]
@EddyVerbruggen - I'm going to close this for now. I appreciate the help, but I don't have any time to make an app demonstrating the issue and the problem is with an app under NDA. Thanks!
