### ISSUE TITLE
Page hangs after transition on Android

### ISSUE THREAD

**Issue by sertal70** [Telerik-Verified-Plugins/NativePageTransitions#176]
Hi all, 
I'm having a weird issue using this plugin, unfortunately it is difficult to provide a plunker or whatever to reproduce, so I'll try to explain with words.

I added the NativePageTransitions plugin to my Ionic 3 app and everything works well both on Android and iOS almost all the time (I'm using the fade transition type).

In the whole app there is only a page that hangs in a very strange way: upon load this page displays a "waiting" spinner while it is waiting for data retrieved from a backend, which are then used to update the view so that they can be displayed in place of the spinner.

The strange thing is that when the view is updated with the data, the page remains stuck with the spinner. Looking at the source code in the debugger, I can see all HTML elements I'm expecting to have but the page doesn't display them. It is like if I didn't call angular detectChanges(), but I did.

The only clue I have is that this page is loaded from a page in which the [cordova-plugin-camera-preview](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview) plugin has been used to take a picture.

I suspect the plugin is the root cause for two reason: 

- If I disable the plugin, everything works well
- it happens on Android only, so it could be an issue in that specific implementation of the plugin

Thanks for help.

[ionic-info.txt](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/files/1699389/ionic-info.txt)

**Comment by sertal70** [comment]
is still plugin support alive?

**Comment by jseremba** [comment]
Am experiencing the same issue, however mine is related to left and right transition on android, am able to slide to a page on the left but fails to do so on the right.

**Comment by tlacroix** [comment]
@jseremba Did you manage to fix this? I'm having the slide right problem too, exactly every second time I call the transition. The slide left works fine.

**Comment by sertal70** [comment]
@tlacroix @jseremba the plugin is no longer maintained (see the disclaimer on top of the README), so I'm going to close the issue.

**Comment by tlacroix** [comment]
@sertal70 I know. I forked and try to maintain a version, we actively use it on 3 projects. This is why I was asking if @jseremba managed to find a fix to his problem, we're experiencing the same on one of the 3 projects.

**Comment by sertal70** [comment]
I understand your point @tlacroix , nevertheless I closed the issue because there is no chance to be managed by the plugin  maintainers.
