### ISSUE TITLE
Statusbar plugin and Slide Animation don't play nice on iOS

### ISSUE THREAD

**Issue by EddyVerbruggen** [Telerik-Verified-Plugins/NativePageTransitions#2]
When including the statusbar plugin to make the top 20 px solid, the new view is placed underneath the statusbar.

**Comment by mabdelfattah** [comment]
Weird! I've this problem, here are the plugin versions:
com.telerik.plugins.nativepagetransitions 0.5.4 "Native Page Transitions"
cordova-plugin-statusbar 1.0.1 "StatusBar"
