### ISSUE TITLE
ajax request fail

### ISSUE THREAD

**Issue by amirabbas** [Telerik-Verified-Plugins/NativePageTransitions#22]
Hi,

I’ve seen something strange again after installing native transition plugin.
I’m not sure that it’s a bug, plugin limitation or my wrong implementation.
My app is a content based news app. Before installing the plugin I’ve checked posts many times and I haven’t any AJAX request fail. I can say that I’ve gone back and forth between first page and detail post page of the app for more 100 times in a row without failing a single request but after installing the plugin around 1/10 of request going to fail. Sometimes 3 successive request fails in a row. I’m using this function for handling errors:

```javascript
error: function(jqXHR, exception) {
            if (jqXHR.status === 0) {
                alert('Not connect.n Verify Network.');
            } else if (jqXHR.status == 404) {
                alert('Requested page not found. [404]');
            } else if (jqXHR.status == 500) {
                alert('Internal Server Error [500].');
            } else if (exception === 'parsererror') {
                alert('Requested JSON parse failed.');
            } else if (exception === 'timeout') {
                alert('Time out error.');
            } else if (exception === 'abort') {
                alert('Ajax request aborted.');
            } else {
                alert('Uncaught Error.n' + jqXHR.responseText);
            }
        }
```

The error code for failed request is the first one (status 0) but Im sure that my connection is ok. The AJAX spinner will spin forever. I think the server has a timeout for a request and after certain amount of time the server will send timeout error but for my case it seems that some AJAX request doesn’t go out of the device. 
this behavior is not limited to kitkat. I've also tested the app of 4.1 and 4.2. when the delay between two request is less than 10 seconds, these failed requests will happen more frequent.
Do you have any idea for this problem or can I do anything to reproduce this condition for you to see it?
Thanks a lot.

**Comment by amirabbas** [comment]
Hi @EddyVerbruggen I've sent you an email few days ago about this problem. I just want to know have you received it? thanks

**Comment by em-ka** [comment]
Hi @amirabbas, I've met similar issues. I've resolved it by not using href option at all (e.g. href: '#someId').

**Comment by amirabbas** [comment]
Hi @em-ka, you are right. after similar suggestion from @EddyVerbruggen I've managed page changes through jQuery mobile and there isn't any ajax request fail. thank you both.
