### ISSUE TITLE
Feature request: modal animation

### ISSUE THREAD

**Issue by bd-arc** [Telerik-Verified-Plugins/NativePageTransitions#24]
Hi @EddyVerbruggen,

First of all, thanks a lot for this great plugin. We used it in one of our apps, and it really improved it!

Surprisingly though, there is one kind of animation that doesn't seem to be supported at the moment: modal. A workaround is to use a slide animation with a vertical direction, but it's not really the same as a modal view covering the current one.

Is it something difficult to implement? Because it would definitely add some more handsomeness to the plugin :)

**Comment by bFlood** [comment]
+1

**Comment by leandroz** [comment]
+1

**Comment by fer8a** [comment]
+1

**Comment by bd-arc** [comment]
@EddyVerbruggen It's been a while, but do you have any update regarding this feature ?

**Comment by EddyVerbruggen** [comment]
Hey @bd-arc sorry I have not, but let's try to do this soon.

Actually, that [classic modal animation](http://www.appgyver.com/supersonic/code_examples#modal-window) link you posted looks to me like a 'slide up' with a very high slowdownfactor, doesn't it?

**Comment by bd-arc** [comment]
@EddyVerbruggen Thank you for your answer Eddy.

Well, the 'slide up' effect is not exactly the same since the old view is moving up too, while it is supposed to stay "still" when the new one is coming in. I hope I am clear enough...

**Comment by EddyVerbruggen** [comment]
Even with a slowdownfactor of 1000? Not tried that but should work..

**Comment by EddyVerbruggen** [comment]
`slowdownfactor:1000` works nicely, but I've now optimized this a bit: you can use `slowdownfactor: -1` to have the old view stay put. Available in master, will soon be part of a release (0.5.8).

**Comment by EddyVerbruggen** [comment]
.. and now for windows as well

**Comment by bd-arc** [comment]
@EddyVerbruggen That's perfect! Thank you very much for implementing this on such a short notice.

By the way, I wasn't aware that we could use such high numbers with `slowdownfactor`; that's good to know.
