### ISSUE TITLE
Fade Transition

### ISSUE THREAD

**Issue by confile** [Telerik-Verified-Plugins/NativePageTransitions#25]
It would be great if you could also support a fade transition.

**Comment by bFlood** [comment]
+1

**Comment by DriesX** [comment]
+1 :-)

**Comment by ericalli** [comment]
+1

**Comment by ericalli** [comment]
Just submitted pull request #46 to add this for iOS.

**Comment by EddyVerbruggen** [comment]
Thanks @ericalli! Good to know: I'm working on an Android version currently.

**Comment by EddyVerbruggen** [comment]
Fade for iOS (and now Android as well) is available in 0.3.0.
