### ISSUE TITLE
Slide transparency

### ISSUE THREAD

**Issue by em-ka** [Telerik-Verified-Plugins/NativePageTransitions#28]
Hi, I'm not sure if it's a feature or a bug :-), but during the left slide transition on iOS (8.1), the slide coming from the right is transparent and fade in at the end of the animation. On Android the slide is solid, without a transparency. On slide right on both platforms a slide is without a transparency.

**Comment by EddyVerbruggen** [comment]
Hi, it's not a feature :)

A few questions so I can pinpoint this:
- Are you running the latest version of the plugin?
- Which device are you seeing this on?
- Does it also happen if you kill the app and your very first transition is to the left? So no native flip, etc has been performed before the transparency pops up.

**Comment by em-ka** [comment]
Hi,
1) yes
2) iPhone 5C, but I'm experiencing it in a simulator too
3) unfortunately yes

But my first description was not totally precise. The slide is not transparent but semitransparent.

**Comment by EddyVerbruggen** [comment]
That's strange, is there a way for me to get my hands on the actual code you're seeing this with?

**Comment by em-ka** [comment]
I've sent you a simplified code snippet via an e-mail. Thank you very much.

**Comment by em-ka** [comment]
I've investigated more. When I use slowdownfactor: 1, everything works fine. When I use default slowdown factor and comment out lines in NativePageTransitions.m, where animations:^{ _screenShotImageView.alpha = lowerLayerAlpha;} is, I can see, that the slide from the right is going under the slide which is leaving the viewport. So the slide coming from the right isn't semitransparent but it looks like, because the slide leaving the viewport has some alpha set. But when I comment out window.plugins.nativepagetransitions.slide from my script, the new slide ("from the right") covers the previous slide as expected. Don't know if it is important, but I'm not using a href attribute. I hope my explanation is clear :-).

**Comment by em-ka** [comment]
Semitransparency issue was caused by an incompatibility with [phonegap-googlemaps-plugin](https://github.com/wf9a5m75/phonegap-googlemaps-plugin). Resolved in 0.2.10 release. Thank you, Eddy!
