### ISSUE TITLE
Incompatibility with Crosswalk

### ISSUE THREAD

**Issue by bd-arc** [Telerik-Verified-Plugins/NativePageTransitions#29]
Hi,

I recently tried to use this plugin in a [Crosswalk](https://crosswalk-project.org/) app, and it didn't go well...

Crosswalk is replacing Android's crappy webview with a Chromium one, and the issue may come from here. Do you think there is a solution to make it compatible?

Here is the relevant ouput :
```bash
-compile:
    [javac] Compiling 20 source files to /project/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /project/src/com/telerik/plugins/nativepagetransitions/NativePageTransitions.java:48: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /project/src/com/telerik/plugins/nativepagetransitions/NativePageTransitions.java:50: error: cannot find symbol
    [javac]       super.onPageFinished(view, url);
    [javac]            ^
    [javac]   symbol: method onPageFinished(WebView,String)
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors
    [javac] 3 warnings

BUILD FAILED
```

**Comment by EddyVerbruggen** [comment]
Perhaps we can make it compatible, we'll need to investigate this.

Btw, your stacktrace also seems to flag an incompatibility with this plugin: https://github.com/Wizcorp/phonegap-plugin-wizUtils

**Comment by JohnCashmore** [comment]
I am also having this issue

**Comment by indiloop** [comment]
I'm interested in using this plugin in our app as well, but we currently use crosswalk on the android side, so I'd have to hold off until this issue is addressed. Hope to see a fix soon :)

**Comment by DaveShapingCloud** [comment]
Hi there, any update on a fix for this?

**Comment by EddyVerbruggen** [comment]
Hi, if you can edit the Java file, then you can get going a little bit by [changing these lines](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/src/android/NativePageTransitions.java#L49-L50) to this:

```
    public void onLoadFinished(XWalkView view, String url) {
      super.onLoadFinished(view, url);
```

And also provide an import for `org.xwalk.core.XWalkView`

However, Crosswalk has not been tested nor is it on our roadmap.

**Comment by JohnCashmore** [comment]
i'd urge you to revisit this as crosswalk adds so much to cordova apps, you don't need to support corsswalk per say its more not requiring things.
