### ISSUE TITLE
Fixed footer shifts down 20px when statusbar plugin is used

### ISSUE THREAD

**Issue by blefebvre** [Telerik-Verified-Plugins/NativePageTransitions#30]
Hey @EddyVerbruggen,

I've found that my footer drops 20px on iOS when NativePageTransitions plugin (version 0.2.9) is used in combination with the org.apache.cordova.statusbar plugin (version 0.1.9). This .gif demonstrates the effect:

![transition_footer](https://cloud.githubusercontent.com/assets/1048207/5764310/f12ce75e-9cbe-11e4-98ce-9b7e0b981862.gif)

I created a (very) basic app to help reproduce the issue: https://github.com/blefebvre/cordova-native-transition-playground

The workaround detailed in https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/15 works as advertised. Since I'm loading a complete page in my sample, I simply added @bau720123's suggestion to my onDeviceReady callback: https://github.com/blefebvre/cordova-native-transition-playground/compare/statusbar-workaround...master

Thanks for all your work on this plugin!

**Comment by EddyVerbruggen** [comment]
Excellent example, thanks for that! I'll take a look.

**Comment by EddyVerbruggen** [comment]
I think I [nailed it](https://www.youtube.com/watch?v=LBA0Pwz2JX8).

Will test some more and push a release.

**Comment by blefebvre** [comment]
Wow - quick turnaround. Thanks, @EddyVerbruggen!

**Comment by EddyVerbruggen** [comment]
You're welcome. v0.2.11 should fix this issue (also for the Drawer animation on iOS btw).
