### ISSUE TITLE
curl transition not working on iPhone 6 Plus?

### ISSUE THREAD

**Issue by agwftl** [Telerik-Verified-Plugins/NativePageTransitions#38]
I'm working on a Phonegap/Cordova app (AngularJS is used to update the views) and would like to use the curl transition to show a hidden menu. All the other transition work as expected, but when I use the curl transition nothing happens. The view gets updated without the transitions. Any ideas why? I'm testing on an iPhone 6 Plus.

**Comment by agwftl** [comment]
I noticed that the Phonegap build service is using the 0.2.2 version. How can I update the plugin to the latest version?

**Comment by EddyVerbruggen** [comment]
The version on PGB is no longer maintained as PGB now supports loading plugins from the [Cordova plugin registry](http://plugins.cordova.io/#/package/com.telerik.plugins.nativepagetransitions) which I try to keep up to date.

See [this blog](http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/) for details.
