### ISSUE TITLE
Unable to pass variable or object to "next" page

### ISSUE THREAD

**Issue by JcDenton86** [Telerik-Verified-Plugins/NativePageTransitions#40]
Hi, I came across with this plugin and I think that it has the means to solve one of the biggest issues of hybrid apps. The animations/transitions that is. 
I am using Onsen UI (a framework such as Ionic - uses AngularJs) which has a lot of great things built-in (including transitions). But it would be even better if this plugin could be included as a default Cordova plugin (so UI frameworks wouldn't have to worry about animations and transitions and would build their logic on top of this plugin). If that's doable :)

Anyway, my issue is that right now I can pass an object from a page to the next one (It is supported through Onsen's navigation pattern). Using the plugin, I am able to make the transition but not to pass the object using a clean way. For instance what I do right now is this:
```
...
var options = {
		title: sight.title,
		description: sight.description,
		image: sight.image
		icon: sight.icon,
		latitude: sight.latitude,
		longitude: sight.longitude
	};
$scope.mynavigator.pushPage('next.html',options);
....
```
and later on the controller of next page I can retrieve the object like this:
```
...
var object = $scope.mynavigator.getCurrentPage();
$scope.title = object.options.title;
$scope.description = ...
```
Is a similar behavior supported?
Thanks in advance!

**Comment by ChuyUX** [comment]
I'm having a similar issue. I'm using Mustache.js for building the templates and fill the content. I have list of items with an anchor each one. The href has this value 'nota.html?id={{id}}'. The shortcode {{id}} it's replaced with the id value of each item, but when I click the link it does the transition but shows nothing. Debugging I found that the id wasn't passed to this page for evaluating and filling the content. Hope you can find soon a solution. Thanks!

**Comment by EddyVerbruggen** [comment]
Are you seeing this on iOS, Android or both?

**Comment by ChuyUX** [comment]
Both

**Comment by EddyVerbruggen** [comment]
@ChuyUX Tried it with iOS slide, no problem found. Please reopen if you can create a simple demo app for me to reproduce it with and I'll happily take a look.

@JcDenton86 For Ionic there's a project that wraps this plugin and auto-enhances Ionic's default transitions. For KendoUI there's something similar. For OnsenUI unfortunately there's not so you'll have to do it yourself. Instead of `pushPage` you could call the plugin directly and pass the object as a variable on `$rootScope`.
