### ISSUE TITLE
The transition didn't finish until i click on the screen

### ISSUE THREAD

**Issue by leandroz** [Telerik-Verified-Plugins/NativePageTransitions#41]
I am using slide right and left for back and forward navigation but i am having and issue with the back transition, the template is updated, but the transition finishes only when i click on the screen.

**Comment by EddyVerbruggen** [comment]
This may be a device and plugin version specific issue, so can you please fill in those details please?

**Comment by leandroz** [comment]
I am using Cordova 4.2.0 and Android 3.6.4, the problem happens on Android and not on iOS, more details that maybe helpful, i am using Angular with UI-Router, and using the href property to trigger the state change.

**Comment by EddyVerbruggen** [comment]
Thanks - which device and Android version are you seeing this on? Also, can you share your project with me perhaps?

**Comment by leandroz** [comment]
Samsung Galaxy S4 with API 19 using Genymotion, i can't share the entire project but yes part of the code, my email is leandro.zubrezki@gmail.com. One more thing, i installed the new version and now in that device the transition is not working, i am trying to install the previous version without success.

**Comment by scottsut** [comment]
i also got this problem,  @leandroz @EddyVerbruggen have you fix it yet or find the way? thx!

**Comment by scottsut** [comment]
@EddyVerbruggen  @leandroz  i think i find the cause, when i uninstall crosswalk, everything run well.

@EddyVerbruggen  could you please check this deep?

**Comment by scottsut** [comment]
i've test in those devices with crosswalk
1. sansum note3     android 4.4    fine
2. huawei c8816     android 4.3    about 5 seconds delay
3. HTC evo 3d       android 4.0.3  must click to trigger the transition

might help

**Comment by EddyVerbruggen** [comment]
@scottsut When using Crosswalk, can you try setting the `androiddelay` to a very low value, like `10`? It's one of the properties you pass to the `slide` transition.

**Comment by scottsut** [comment]
@EddyVerbruggen  thank you very much ! that is the point.
it seems crosswalk increase 10 times of the androiddelay, and it get worse at <4.4 android devices. i curious what cause the problem?  do you kown @EddyVerbruggen ?

**Comment by Exilz** [comment]
@EddyVerbruggen any update on this ? I'm still experiencing this problem with any Android device < 4.4. Even with very low values, this still doesn't work. I tried with -1 and executePendingTransition(), still no luck. I have to touch the screen to trigger the animation.
It works perfectly on Android 5, though.

**Comment by CramericaIndustries** [comment]
Same problem here, I also have to touch the screen to trigger the animation.
Real device, running on Android 4.1.2 (Samsung GT-S5310, Kernel 3.0.15-1225838)

**Comment by CramericaIndustries** [comment]
@EddyVerbruggen I did some research, seems to be the same problem as described here:
[http://stackoverflow.com/questions/16238513/animation-not-starting-until-ui-updates-or-touch-event](http://stackoverflow.com/questions/16238513/animation-not-starting-until-ui-updates-or-touch-event)

The problem was gone as soon as I added `view.requestLayout();` before each of the  `view.startAnimation(...);` calls in the `doXyTransition()` methods in the NativePageTransitions.java file.

**Comment by bd-arc** [comment]
@EddyVerbruggen If ```layout.invalidate();``` is not bound to break something, I think that incorporating this fix would save a lot of lives :)

**Comment by EddyVerbruggen** [comment]
Hey @CramericaIndustries thanks a lot for your research! Would you be up for a PR? If not then I'll try to do it soon, but if you'd like to contribute please add that line of code to the various methods and guard it with a <4.4 version check like done in other parts of the code.

**Comment by CramericaIndustries** [comment]
Hi @EddyVerbruggen, I think that the modification should be tested first by @scottsut, @leandroz and @Exilz just to be sure that this really does the trick. Also I'm not very experienced with git and github so I would prefere if you would check in the modification.

**Comment by EddyVerbruggen** [comment]
Hey @CramericaIndustries I've just pushed the changes to the master branch, if you grab it you'll get version `0.6.5-dev` which includes that line of code you proposed (for slide only since I've never had any clues it's a problem for other transitions).

I didn't reproduce the issue so I'm curious to learn from guys having the problem if this fixes it. I didn't see regression either, so that's good ;)

**Comment by Exilz** [comment]
@EddyVerbruggen @CramericaIndustries Looks like this fixed the problem with the slide transition on my Samsung Galaxy S3. Gratz !
I didn't try the other animations, though.

If someone encounters the same problem with another effect, here's the hack I used before the proper fix.

```
                    if (this.isCrappy) { // Old and sh*tty devices
                        // ¯\_(ツ)_/¯ Trigger a repaint on android < 4.4
                        // so the transition is properly released
                        setTimeout(() => {
                            document.body.style.transform = 'translateZ(0)';
                            setTimeout(() => {
                                document.body.style.transform = '';
                            }, 80);
                        }, 0);
                    }
                    this._plugin.executePendingTransition();
```

**Comment by CramericaIndustries** [comment]
@EddyVerbruggen I've tested` 0.6.5-dev` on the Samsung GT-S5310 (Android 4.1.2) and the problem didn't show up.

**Comment by EddyVerbruggen** [comment]
Sweet, leaving this open just a little longer to make sure no regression pops up, but I think we'll be fine.

**Comment by bd-arc** [comment]
@EddyVerbruggen After testing the fix thoroughly, I can say that the issue didn't show up for me either. I'm eager to see this published to npm ;)

@CramericaIndustries Thank you very much for finding this solution! This issue has been haunting me for more than a year and a half...

**Comment by EddyVerbruggen** [comment]
@bd-arc @Exilz @CramericaIndustries Awesome, thanks for your test efforts!

And major thanks to @CramericaIndustries for sharing this workaround!

npm has been updated with 0.6.5
