### ISSUE TITLE
Transition Image is shown when using Slide right/down

### ISSUE THREAD

**Issue by stephan1234** [Telerik-Verified-Plugins/NativePageTransitions#43]
Hi,

I found an issue while implementing the plugin in my app. Many thanks at first for this great plugin!

If you use the slide down or right, the transition works, but after it ends, the image is shown again. I have solved this issue by placing

bringToFront(webView);

at line 469.

Maybe you can implement this in the next release.

Best & thanks again
Stephan

**Comment by EddyVerbruggen** [comment]
Hi,

I can imagine that indeed solves your issue. Did you test this one different Android devices as well?

I don't have the issue on my testdevices but I will incorporate the change if I don't see any side effects.

**Comment by hkcity1111** [comment]
This fixing help me to remove problem of blink of previous image too. Thanks a lot!!
