### ISSUE TITLE
'WebKit/WebKit.h' file not found

### ISSUE THREAD

**Issue by iourt** [Telerik-Verified-Plugins/NativePageTransitions#44]
'WebKit/WebKit.h' file not found
#import <WebKit/WebKit.h>

Can you tell me which packages I need to install or what else I need to do? 

thanks

**Comment by EddyVerbruggen** [comment]
Hi,

WebKit.h is part of the iOS 8 SDK. Are you building with XCode 5 perhaps, or an older Cordova version in AppBuilder?

**Comment by iourt** [comment]
hi

thanks
