### ISSUE TITLE
Timing is irregular in app, need start/end methods perhaps?

### ISSUE THREAD

**Issue by braco** [Telerik-Verified-Plugins/NativePageTransitions#45]
Trying to use this with React. Having a hard time getting the delays working correctly. Sometimes the old content is still visible. Seems dependent on the platform and general lag. Using href doesn't fix the issue.

It would be handy to have something like this:

```
nativepagetransitions.startSlide({...})
```
in the React view controller:
```
// This is like a "page is finished" event
componentDidMount: -> nativepagetransitions.end({})
```

That way we can 1. screenshot the current content, 2. listen for a "finish" event in whatever framework the end user has, then 2. swap the content out. The main idea is just to give that control to the user.

Maybe
```
nativepagetransitions.prepare({type: 'slide', ...});
nativepagetransitions.perform();
```

**Comment by KODerFunk** [comment]
+1 need in React.js application with react-router instead/in `ReactCSSTransitionGroup`

**Comment by EddyVerbruggen** [comment]
A while ago I added the ability to manually control when the transition kicks in (`executePendingTransition`). You should be able to integrate that with react. I know of a popular Angular wrapper that uses this method successfully.

**Comment by KODerFunk** [comment]
Thank you @EddyVerbruggen 2!
