### ISSUE TITLE
Can't compile on Cordova Android 5.0

### ISSUE THREAD

**Issue by mluria** [Telerik-Verified-Plugins/NativePageTransitions#49]
I get all sorts of errors related to CordovaWebView

**Comment by bau720123** [comment]
I have the same problem
when I use
```
cordova plugin add nativepagetransitions
cordova build android
```
it will show the error message
http://www.littlebau.com/cli/nativepagetransitions_cli.gif

**Comment by jonathan-clark** [comment]
I am getting the same error using Android 4.4. Any solutions?

**Comment by bau720123** [comment]
problem solved when I use
```
cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions.git
cordova build android
```

**Comment by EddyVerbruggen** [comment]
Hey guys, I just fixed this issue and released 0.4.0. Will publish it to cordova plugin registry soon.

**Comment by globalizeme** [comment]
Hi Can you please help me transition effect not working for me here the same code  which i tried.

git@github.com:globalizeme/effect.git

**Comment by EddyVerbruggen** [comment]
@globalizeme plz open an issue in [your repo](https://github.com/globalizeme/effect) and mention my handle
