### ISSUE TITLE
the "Fade" function seem have no really affect

### ISSUE THREAD

**Issue by bau720123** [Telerik-Verified-Plugins/NativePageTransitions#54]
hi @EddyVerbruggen 
according to this
http://plugins.telerik.com/cordova/plugin/native-page-transitions

when I use 
```
var options = {
  "duration"       :  600, // in milliseconds (ms), default 400
  "iosdelay"       :   50, // ms to wait for the iOS webview to update before animation kicks in, default 60
  "androiddelay"   :  100
};
window.plugins.nativepagetransitions.fade(
  options,
  function (msg) {alert("success: " + msg)}, // called when the animation has finished
  function (msg) {alert("error: " + msg)} // called in case you pass in weird values
);
```

in Android and iOS，it will trigger the success callback，but...it seem have no really animation show up
in winphone，it will trigger the success callback，and print "Invalid action"，is it because that "Fade" function not ready for wp8 ?

**Comment by EddyVerbruggen** [comment]
Hi,

iOS and Android: if you're not changing the content (options.href param) you will not notice a change.

WP: you're right, it's not supported at all (doc updated).

Thanks,
Eddy

**Comment by bau720123** [comment]
got it
thanks @EddyVerbruggen
