### ISSUE TITLE
Slide doesn't work with 4.0 and 4.1 versions, but works with 3.0

### ISSUE THREAD

**Issue by Lanayx** [Telerik-Verified-Plugins/NativePageTransitions#57]
The issue was reproduced on two devices with android 4.1 and 4.2. Plugin 4.0 version throws an exception and 4.1 just displays the same view after the slide finishes (in console it writes "Probably running inside a companion app, your app may crash if your html file is not in the root!"). Cordova version is 3.6.4. Everything works fine in 3.0 plugin version.

**Comment by EddyVerbruggen** [comment]
Hi @Lanayx can I perhaps get my hands on your sourcecode to figure out what's causing this problem?

**Comment by Lanayx** [comment]
the code is pretty simple. I'm using telerik appbuilder, navigation to the remote view.
window.plugins.nativepagetransitions.slide(
            {
                "href": "#views/profileView/profile.html",
                "direction": "left"
            }
![clip2net_150706082510](https://cloud.githubusercontent.com/assets/3329606/8516111/987afc82-23b8-11e5-91bb-c2bc06fb9fa0.png)

**Comment by EddyVerbruggen** [comment]
I don't think the plugin expects a URL like that (anymore). I mean, the href starts with a '#' but ends with '.html', this may confuse some of the logic in the plugin.

Can you share that project with me so I can debug it a bit?

**Comment by Lanayx** [comment]
I've tried to remove hash sign but it didn't help. Please take a look at my project
https://drive.google.com/open?id=0B1X8p1WKkhv1eGZFZmJTeXJsN2c

**Comment by EddyVerbruggen** [comment]
@Lanayx I've imported your project [here](https://github.com/EddyVerbruggen/NativeTransitionsIssue) and created a new AppBuilder project, but after starting the app on my Android device it remains at the screen saying 'Loading...'. Sounds familiar?

Btw, I say the plugin version is at 0.3.0, can you please update to the latest version?

**Comment by Lanayx** [comment]
It seems you've corrupted smth during import (I've noticed that app identifier is different, might be something else too), because that project fails for me too on Loading, displaying Chromium error in the log. The original project in the archive runs well and should display Login button which should redirect you to another view after click. The reason I set 0.3.0 is that you can see it working. It fails after changing to 0.4.* version.

**Comment by EddyVerbruggen** [comment]
@Lanayx You're probably right - do you simply have a github repo I can clone?

**Comment by Lanayx** [comment]
Try this https://github.com/Lanayx/CordovaNavigationIssue

**Comment by Lanayx** [comment]
@EddyVerbruggen Have you reproduced the issue?

**Comment by EddyVerbruggen** [comment]
Hi @Lanayx I've installed your project locally with all your plugins and captured [this video](https://dl.dropboxusercontent.com/u/10061342/NativePageTransitions-issue-57.mov) in an Android 4.1.1 emulator. That looks correct, right?

On a 4.4.4 device all was fine too.

Then I deployed [your apk](https://github.com/Lanayx/CordovaNavigationIssue/blob/master/bin/Debug/Android/RadrugaMobile.apk) to my 4.4.4 device and that one was stuck on the 'Loading...' screen.

**Comment by Lanayx** [comment]
@EddyVerbruggen Yes, the behavior in the video is correct. Tha apk was built up by Telerik for my device, so I'm not sure if it should have worked for you too. What is more important is that the project works now with the 0.3.0 plugin version, but doesn't with latest ones.

**Comment by Lanayx** [comment]
Find a plugin issue in _validateHref, localUrl.lastIndexOf('/') should be replaced by localUrl.lastIndexOf('/index.html')
