### ISSUE TITLE
about the "0.4.1" version

### ISSUE THREAD

**Issue by bau720123** [Telerik-Verified-Plugins/NativePageTransitions#63]
hi @EddyVerbruggen 
according to this
http://plugins.telerik.com/cordova/plugin/native-page-transitions
I saw there is a new version 0.4.1

but for now in "plugins.cordova.io" seem only have a old 0.4.0 (I think it is because "plugins.cordova.io" become readonly)
http://plugins.cordova.io/#/package/com.telerik.plugins.nativepagetransitions

so...is there any plan that transfer this plugin to npm ?

**Comment by pavei** [comment]
+1

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
for now is 0.4.2
just feedback and hope have a npm version
