### ISSUE TITLE
Callback Issue

### ISSUE THREAD

**Issue by samichkeir** [Telerik-Verified-Plugins/NativePageTransitions#68]
Callback on instance doesn't work .

function changePage(hrf) {
	    window.plugins.nativepagetransitions.slide(
	    		{
	    			 "direction"        : "left", 
	    			  "duration"         :  500, 
	    			  "slowdownfactor"   :    3,
	    			  "iosdelay"         :  100, 
	    			  "androiddelay"     :  10,
	    			  "winphonedelay"    :  250, 
	    			  "fixedPixelsTop"   :    0, 
	    			  "fixedPixelsBottom":0,
    	          "href": hrf
    	        },
	        function () {
	        	alert(5);
	        },
	        function (msg) {
	        	// alert('error: ' + msg);
	        });
}
what is the problem ? 
Thanks

**Comment by EddyVerbruggen** [comment]
Which platform is this, and better still: can you share a small demo app reproducing this issue?

**Comment by leobetosouza** [comment]
Same here. Transition works, but the callback is not fired. On all transitions.

Android 5.1

**Comment by EddyVerbruggen** [comment]
@leobetosouza can you perhaps share your project with me? I have a demo app which alerts in the successhandler just fine. This is my code btw:

```js
         function letsSlide() {
            var options = {
              "direction"        :  "right", // 'left|right|up|down', default 'left' (which is like 'next')
              "duration"         :     2500, // in milliseconds (ms), default 400
              "slowdownfactor"   :        3, // overlap views (higher number is more) or no overlap (1), default 4
              "iosdelay"         :      300, // ms to wait for the iOS webview to update before animation kicks in, default 60, -1 is auto
              "androiddelay"     :      300, // same as above but for Android, default 70, -1 is auto
              "winphonedelay"    :      250, // same as above but for Windows Phone, default 200,
              "fixedPixelsTop"   :       30, // the number of pixels of your fixed header, default 0 (iOS and Android)
              "fixedPixelsBottom":       60  // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
            };
            window.plugins.nativepagetransitions.slide(
              options,
              function (msg) {alert('done')}, // called when the animation has finished
              function (msg) {alert("error: " + msg)} // called in case you pass in weird values
            );
         }
```

**Comment by leobetosouza** [comment]
I'm trying with this fork of the ionic-native-transitions plugin: https://github.com/leobetosouza/ionic-native-transitions/blob/develop/dist/ionic-native-transitions.js#L292

**Comment by EddyVerbruggen** [comment]
@leobetosouza aha, if you can reproduce it with this plugin directly (not wrapping it with that Ionic plugin) then please reopen. Otherwise you'd better file an issue there.

**Comment by leobetosouza** [comment]
@EddyVerbruggen i will try... if you read the code that I linked you'll see that i'm using `window.plugins.nativepagetransitions`...

so... tks
