### ISSUE TITLE
Phonegap build issue with cli-5.2.0

### ISSUE THREAD

**Issue by lengoyvaerts** [Telerik-Verified-Plugins/NativePageTransitions#72]
When I use the latest version like so:
![config](https://cloud.githubusercontent.com/assets/14726469/10222843/6e06d088-6856-11e5-81b3-eb6720017ab7.png)

The Phonegap Build fails with following message: 
![error](https://cloud.githubusercontent.com/assets/14726469/10222676/940526c8-6855-11e5-87ee-706ef7323251.png)

Build log:
http://pastebin.com/Ks6zVieX

**Comment by EddyVerbruggen** [comment]
Indeed, that version doesn't support cordova-android 4. Try setting `source="plugins.cordova.io"` in your `gap:plugin` and remove the version attribute.

**Comment by lengoyvaerts** [comment]
This no longer works when using Phonegap Build because plugins.cordova.io has been deprecated

**Comment by EddyVerbruggen** [comment]
It's now on npm as well.

**Comment by RedEars** [comment]
I am experiencing the same problem now using the npm version and Phonegap 3.7.0.
Any ideas?
