### ISSUE TITLE
Better control when to take screenshot and animate

### ISSUE THREAD

**Issue by NgYueHong** [Telerik-Verified-Plugins/NativePageTransitions#76]
Here I would like to request more control on when to take screenshot and animate. 

Currently, the plugin work in the way that we have to put the estimate delay for the first & second screenshot. Using the delay method will always result in, it will be either animated too soon or too late. This is something very hard to work on as different devices has different performance. The animation that look good on this device may be animated too soon on other device.

So, it would be great if there is the API for us to do things like, now take the first screenshot. Then, another command to request taking second screenshot and animate it. This allow us to have more control based on our program logic and avoided being animated too soon or too late.

I really hope to see this feature will be implemented soon. Thank you.

**Comment by EddyVerbruggen** [comment]
That's a great idea. See #62.

I hope to be able to implement this soon, but I'm not currently working on it.
