### ISSUE TITLE
[ANDROID] Transitions not stable

### ISSUE THREAD

**Issue by shprink** [Telerik-Verified-Plugins/NativePageTransitions#78]
Hi,

I am the author of https://github.com/shprink/ionic-native-transitions and I am experiencing problems with native transitions on Nexus 9, Marshmallow and Crosswalk 1.3.1. The flip (left or right) transition for instance crashes the app and the slide (left or right) works from time to time and when it does 50% of the time I have a black screen below the animation.

Hope this help. Let me know if I can help in any ways.

**Comment by EddyVerbruggen** [comment]
Hi, did you set this is `config.xml`?
```xml
<preference name="CrosswalkAnimatable" value="true" /> 
```

**Comment by shprink** [comment]
I did yes.

**Comment by shprink** [comment]
https://github.com/shprink/ionic-native-transitions/blob/develop/config.xml

**Comment by shprink** [comment]
Interesting report : https://github.com/shprink/ionic-native-transitions/issues/12

**Comment by EddyVerbruggen** [comment]
Just in case it was not clear: -1 was only added for slide. I'm testing this and if ppl like it it will be added to other transitions as well.

**Comment by Stylemayster** [comment]
I must say +1 for the addition of -1  Definitely more reliable than a fixed delay :)

**Comment by shprink** [comment]
Huuum @EddyVerbruggen ! thanks for the clarification. -1 is just what I have been waiting for... too excited, you can't blame me :)

**Comment by NgYueHong** [comment]
@EddyVerbruggen Anyone who don't want to see the same page being transition in would love it (`-1`). So, no worry about it and we are all too excited & can't wait for this feature to be fully officially supported. Anyone who don't loves it, can still always set the `androiddelay` or `iosdelay` value greater than `-1` and use as traditional method right?

**Comment by EddyVerbruggen** [comment]
Hiya, I've just released 0.5.0 which supports the `-1` delay on iOS and Android for ALL transitions.
Woohoo!

**Comment by shprink** [comment]
OMG OMG OMG OMG!!!!!! @EddyVerbruggen you are amazing!

**Comment by Stylemayster** [comment]
@EddyVerbruggen  Nice job! It exactly what we need!!! Thx =D
