### ISSUE TITLE
slide-left ignores fixedPixelsTop and fixedPixelsBottom

### ISSUE THREAD

**Issue by mccraigmccraig** [Telerik-Verified-Plugins/NativePageTransitions#80]
with `[com.telerik.plugins.nativepagetransitions 0.5.1]` on iOS slide left and right are both working fine, but slide-left is ignoring the `fixedPixelsTop` and `fixedPixelsBottom` options (whereas slide-right is honouring them as expected)

**Comment by EddyVerbruggen** [comment]
Hmm, will look into it asap!

**Comment by EddyVerbruggen** [comment]
Would you mind testing the new version from master (0.5.1dev)?

**Comment by mccraigmccraig** [comment]
that does the trick :)

thank you !

**Comment by EddyVerbruggen** [comment]
Awesome! Thanks for reporting the issue and testing it swiftly :+1:
