### ISSUE TITLE
move to npm?

### ISSUE THREAD

**Issue by tbro028** [Telerik-Verified-Plugins/NativePageTransitions#81]
Hi,
Are you able to move the plugin to npm? Currently using cordova.io for phonegap build but it only seems to have old version and I think the trend is to move to npm anyway?

Awesome work btw

**Comment by EddyVerbruggen** [comment]
It's up there now!
https://www.npmjs.com/package/com.telerik.plugins.nativepagetransitions

**Comment by bau720123** [comment]
thanks @EddyVerbruggen

**Comment by tbro028** [comment]
legen...wait for it... dary
