### ISSUE TITLE
Crash on Android 4.3 with Crosswalk

### ISSUE THREAD

**Issue by Exilz** [Telerik-Verified-Plugins/NativePageTransitions#82]
After updating Crosswalk to version 1.3.0, my app crashes at startup.
I've set CrosswalkAnimatable to true and I'm using the latest version of this repo.

I'm not using the new negative delay feature.

Here is the log when I'm starting the application.

`E/AndroidRuntime(25367): java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.xx.xx/fr.xx.xx.MainActivity}: java.lang.UnsupportedOperationException: setLayerType
E/AndroidRuntime(25367): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
E/AndroidRuntime(25367): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
E/AndroidRuntime(25367): 	at android.app.ActivityThread.access$700(ActivityThread.java:159)
E/AndroidRuntime(25367): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
E/AndroidRuntime(25367): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25367): 	at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(25367): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
E/AndroidRuntime(25367): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25367): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(25367): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
E/AndroidRuntime(25367): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
E/AndroidRuntime(25367): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(25367): Caused by: java.lang.UnsupportedOperationException: setLayerType
E/AndroidRuntime(25367): 	at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:57)
E/AndroidRuntime(25367): 	at org.xwalk.core.XWalkView.setLayerType(XWalkView.java:615)
E/AndroidRuntime(25367): 	at com.telerik.plugins.nativepagetransitions.NativePageTransitions.enableHardwareAcceleration(NativePageTransitions.java:723)
E/AndroidRuntime(25367): 	at com.telerik.plugins.nativepagetransitions.NativePageTransitions.initialize(NativePageTransitions.java:101)
E/AndroidRuntime(25367): 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:54)
E/AndroidRuntime(25367): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
E/AndroidRuntime(25367): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:95)
E/AndroidRuntime(25367): 	at org.apache.cordova.PluginManager.init(PluginManager.java:84)
E/AndroidRuntime(25367): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
E/AndroidRuntime(25367): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:150)
E/AndroidRuntime(25367): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:220)
E/AndroidRuntime(25367): 	at fr.archriss.aixmobile.MainActivity.onCreate(MainActivity.java:32)
E/AndroidRuntime(25367): 	at android.app.Activity.performCreate(Activity.java:5372)
E/AndroidRuntime(25367): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
E/AndroidRuntime(25367): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
E/AndroidRuntime(25367): 	... 11 more`

Thanks a lot for your help.

**Comment by EddyVerbruggen** [comment]
Thanks for the stacktrace, I hope to take a look at this later today.

**Comment by EddyVerbruggen** [comment]
Fixed in master, please update and test it if you can.

**Comment by Exilz** [comment]
It's working like a charm now, thanks a lot.
Meteor + Crosswalk 1.3 + Android 4.3 (Galaxy S3).
