### ISSUE TITLE
flip background color change?

### ISSUE THREAD

**Issue by tbro028** [Telerik-Verified-Plugins/NativePageTransitions#84]
Not a defect but not sure where to make a feature request. Would be awesome if we could change the background color of the flip. At the moment it is black and would be good to make it fit in with app theme better. Not sure if it's possible...

**Comment by tbro028** [comment]
p.s this is an awesome plugin. improves my ionic app alot.

**Comment by EddyVerbruggen** [comment]
Hi, nice request ;)

Picked it up immediately - you can now pass in a `backgoundColor` property on iOS and Android as part of the `flip` animation. It expects a value like `#FFFF00` (so the well known CSS style `#RRGGBB`). [See the demo as well.](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/demo/index.html#L67)

Available in master (`0.5.4-dev`).

**Comment by tbro028** [comment]
legend.

**Comment by EddyVerbruggen** [comment]
:beers:
