### ISSUE TITLE
Feature Request - Native Material Design Transition

### ISSUE THREAD

**Issue by AlexEntrepreneur** [Telerik-Verified-Plugins/NativePageTransitions#86]
Hi Guys, 

I would love to have a material design transition within this plugin, which would be the default for Android. Descriptively, it is a combination of both the "fade" and "slide-up" transitions.

You can see Ionic's implementation as a visual reference here: http://ionicframework.com/docs/v2/components/#navigation

Looking forward to it!

**Comment by shprink** [comment]
That could be great!

**Comment by EddyVerbruggen** [comment]
Guys,

@AlexEntrepreneur, @shprink I'm not clear on what it should look like - that page shows the same animation you'd get with `slide:'left'` and `slowdownfactor:4`. It's not the slide-up/fade you mentioned. Do you have a small video showing what you mean exactly?

**Comment by AlexEntrepreneur** [comment]
@EddyVerbruggen If you look on the same page, and toggle to "Android" above the mobile device, the design and transition is different.

**Comment by srameshr** [comment]
@EddyVerbruggen Any thing on this?

**Comment by EddyVerbruggen** [comment]
The animation referred to is one of Ionic, but is it the real material animation? I mean, when 'closing' the page it animates the old view a bit down and quickly fades it out. I though the real one only did a slide down, but I'm not sure. That could be achieved by using slide:up and slide:down with a very high slowdownfactor btw.

I'd rather base this work on an actual native animation. Has anyone by any chance seen an example of that? Best would be a video.

**Comment by srameshr** [comment]
Ionic here as tried to emulate the actual native animation.
Yeah, I will provide a video, that would be best example I guess.

https://www.dropbox.com/s/0v372amm4cq3u3u/2016-01-21-17-40-56_screenRecording.mp4?dl=0

As you can see, I am navigating from master to detail pattern in this weather app. Each time I click on a city, observer the navigation. It kind of fades in and slides up simultaneously.

**Comment by EddyVerbruggen** [comment]
Thanks! Looks very much like Ionic's indeed. 

Any suggestion for a good name for this transition? slideOver or something? I hope to give this a shot soon. Android first.

**Comment by srameshr** [comment]
You are the man!
Fade + slide = flide :)

Yeah! Hope to see it soon to!

**Comment by shprink** [comment]
Slide + Fade = Slide

**Comment by EddyVerbruggen** [comment]
I gave this some thought yesterday and I think it's best to integrate this into `slide` (with a new optional param).

By the way, there's also a variant of `slide` now where you can have the old page stay put and slide over the new one. When going back the new page will stay put and the old one will transition away. It's the same as you were able to do already by passing in a high `slowdownfactor` like `1000`, but you can now more elegantly do this by passing in `slowdownfactor: -1`.

The main difference between `slowdownfactor: -1` and the material thing requested here is that the new page shouldn't slide in from outside the screen, but almost from where it needs to be. The reverse transition needs to slide it away a bit and then quickly fade away.

**Comment by srameshr** [comment]
ok slide with an option param sounds just fine.

**Comment by EddyVerbruggen** [comment]
Guys, need your input. Is this what you mean (iOS impl)? https://www.youtube.com/watch?v=VayaLuiVBQM

**Comment by srameshr** [comment]
Ummm... No, it looks quite different. Or is it just me?

**Comment by EddyVerbruggen** [comment]
Please be specific about the differences you see. Note that you will be able to control the nr of pixels it slides and how quickly it animates.

**Comment by srameshr** [comment]
I really cant make it out. Can you change the background between both the screen. Put something contrasting instead of the default cordova logo

**Comment by kioku** [comment]
It looks quite good!

Tweaking the number of pixels, and the animation duration should bring it home.

Question - can you control both the slide, and the fade duration?

**Comment by EddyVerbruggen** [comment]
@srameshr @kioku I've tweaked it a bit further: https://www.youtube.com/watch?v=QLp5MnPmSNc based on @srameshr's screenrecording.

Setting a separate value for fade duration is not possible at the moment. The Android implementation will take priority over it anyway.

If this comes close then I will push it.

**Comment by AlexEntrepreneur** [comment]
@EddyVerbruggen This is looking really good! With a few tweaks it should be spot on.

**Comment by EddyVerbruggen** [comment]
Cool! I've pushed it to master.

The "material up" transition in the last video uses `slide` with these options:

```js
var options = {
  slidePixels : 16, // "material" effect, will only slide for this amount of px, default full page. Only makes sense / works correctly with "direction" up or down
  href :  "second.html",
  direction : "up",
  duration : 200, // in milliseconds
  slowdownfactor : -1, // the previous page doesn't scroll away
  fixedPixelsTop : 0, // set > 0 for a fixed header
  fixedPixelsBottom : 0  // ditto, for footer
};
```

**Comment by AlexEntrepreneur** [comment]
@EddyVerbruggen is there a way to enable this plugin for one platform and not another (e.g for Android and not iOS)? Apologies if this is already documented.

**Comment by EddyVerbruggen** [comment]
Use the device plugin to check the platform?

**Comment by AlexEntrepreneur** [comment]
I'll have a look

**Comment by srameshr** [comment]
This is amazing! I will give it a try.

**Comment by kioku** [comment]
I have tried it out, and I can agree. It's amazing!

Will the android implementation follow soon?

**Comment by EddyVerbruggen** [comment]
Android support just landed, same usage as on iOS (see below).
Let me know what you think and I'll release a new version (0.6.0) to npm.

```js
var options = {
  slidePixels : 20, // this triggers the material slide effect, leave out/set to 0 for full page slide
  href :  "second.html",
  direction : "up", // and "down" for the reverse effect
  duration : 220, // in milliseconds
  slowdownfactor : -1, // the previous page doesn't scroll away
};
```

**Comment by tbro028** [comment]
Hi,
I noticed you've released 0.6.0 can you do the magic to make it available
in PGB?

Thanks!

**Comment by EddyVerbruggen** [comment]
@tbro028 this should do the trick (I don't even think the `gap:` prefix is required btw):

```xml
<gap:plugin name="com.telerik.plugins.nativepagetransitions" source="npm" />
```

**Comment by EddyVerbruggen** [comment]
Closing for now, if you find any issue please create a new one.
