### ISSUE TITLE
Android Slide Transition: White Screen Issue

### ISSUE THREAD

**Issue by nickabond** [Telerik-Verified-Plugins/NativePageTransitions#88]
When I use the slide transition with these parameters:

window.plugins.nativepagetransitions.slide({
	"href" : address,
	"iosdelay": 20,
        "androiddelay":200,
	"duration":400,
});

The transition works great on iOS, however, on Android I get a white screen right before the next page comes up. I have tried setting the android delay low (10) and high. but I still can't resolve this. I am using crosswalk 15 and I'm on an Android 4.4 device. Any thoughts?

**Comment by EddyVerbruggen** [comment]
Is this with that 'animatable' setting enabled from xwalk? If so, can you share your Android project with me perhaps?

**Comment by nickabond** [comment]
Yep I set this preference already:

<preference name="CrosswalkAnimatable" value="true" />

The animation seems to work. It just shows a white screen for about a second, and then the new page shows. It is an Intel XDK project, so do you just want the whole Intel XDK project folder? Not sure what would work best for you?

**Comment by EddyVerbruggen** [comment]
I have no XDK experience - can I simply run it in Android Studio? If so, please send it to me at eddyverbruggen at gmail.

**Comment by nickabond** [comment]
No I don't think it will let you, since it's an Intel XDK project. However, I could send you my www folder, and a list of the plugins I'm using? Would that work?

**Comment by EddyVerbruggen** [comment]
I could take a peek but don't expect too much..

**Comment by nickabond** [comment]
You know what I have quite a few plugins, so I don't want to cause you a lot of extra work. You might be able to help me by answering a few questions. When the page is transitioning to another it takes a snapshot of the page right? Is it possible that my device is taking that snapshot too early before the page renders?

**Comment by EddyVerbruggen** [comment]
If the screenshot is completely white it's not a matter of timing, but rather it captures an incorrect view. Can you easily try a few of the older versions of this plugin and see if that makes a difference? I had to make a few changes for crosswalk recently.

**Comment by nickabond** [comment]
Okay got it. Yeah I'll go ahead and test several of the older versions and get back to you.

**Comment by nickabond** [comment]
Alright so I have some good news. The 0.5.3 version of the plugin does not have that white screen problem. So there must be something that happened after the 0.5.4 release. However, on the 0.5.3 version there is a little bit more of a delay between when I tap and when the transition starts as it compares to the 0.5.4 release? I have an android delay of 0 and a duration of 100 so I think it should be fairly zippy?

**Comment by EddyVerbruggen** [comment]
Interesting! Are you able to change [this file](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/src/android/NativePageTransitions.java) in your project and try a few things?

**Comment by nickabond** [comment]
Yes I absolutely can! Just let me know what changes to make.

**Comment by nickabond** [comment]
Did you want me to try the one you pointed to in the last post or were you making up another?

**Comment by EddyVerbruggen** [comment]
Can't really find anything.. A bit of a longshot, but are you using `flip` as well in your app? Perhaps even with a custom backgroundcolor?

**Comment by nickabond** [comment]
Thanks so much for helping Eddy! I ended up figuring it out after looking through your code and my own. Basically in the 0.5.3 version of your code you had a couple of lines in there that waited for the entire web view to be loaded before the transition proceeded. It appears that that code was removed in the 0.5.4 and up versions? 

As I stated before the was a white screen in 0.5.4 and up initially, and a long delay between when I pressed a menu button and when the transition actually started in 0.5.3. A key detail helped me figure it out. On the 0.5.4 version, I noticed that when I tapped the white screen with my finger the scroll bar showed up. It all made sense then!

It was still loading the web view in the 0.5.4 version, and that's why there was a white screen for a second or so. When I ran timeline tests on the app, I realized that the Jquery mobile and the regular Jquery framework were taking 0.7 seconds to parse, and that is what was causing the white screen and delayed web view loading! Someone else might run into this problem depending on what frameworks they do, so I thought it was important to type everything out. By taking out the Jquery mobile framework and slimming down the regular Jquery framework I was able to get rid of the delay completely. It's nice to have frameworks to use, but they can definitely get too heavy sometimes. I also deferred the loading of several of my other scripts, which made things even faster. 

You're plugin is great, and this was mostly lessons learned on my end! If anyone else has an issue like this in the future, just direct them to this post.

**Comment by EddyVerbruggen** [comment]
Hey Nick, are you perhaps family of James? Judging by your investigation skills I think you are 

Thanks for elaborating on your experiences. 

Eddy

**Comment by insaneinc01** [comment]
I have a similar issue but on iOS. It works perfect on the iOS emulator. The issue is only when I run it on the iPhone. 

The snapshot that is taken is always of a white screen. The white screen then animates as per the drawer settings. This happens both for drawer 'open' and 'close'. So its apparent that the screenshot taken is of the white screen. 

Very weirdly, this doesn't happen on the iOS emulator. I tried setting various values for iosdelay, even tried manually trigger the animation using executePendingTransition. 
BUT since the screenshot is of a whitescreen, nothing works. 

Any ideas please?

**Comment by EddyVerbruggen** [comment]
@insaneinc01 That fix was for fade. I can imagine drawer has the same issue. I'll try and fix that now.

**Comment by EddyVerbruggen** [comment]
#118 was a similar fix for drawer - that's 0.6.2. Does this problem occur with 0.6.2 as well? I'm experiencing this with flip, but that wasn't fixed yet (doing that now).
