### ISSUE TITLE
Callback function not called

### ISSUE THREAD

**Issue by Ibrahimwatfa** [Telerik-Verified-Plugins/NativePageTransitions#89]
Dear Support,

The callback function once the transition is done is not called at all.
I tried several things from the documentation but still not reaching the callback function on transition end.

Please advise.

**Comment by EddyVerbruggen** [comment]
Which platform, which plugin version, and which plugin feature (sample code) are you using? Thanks!

**Comment by Ibrahimwatfa** [comment]
I'm developing and Cordova Android Application.
The plugin version is  0.5.4

Below is a sample code:

var options = {
		"direction"        : 'left',
		"duration"         :  500,
		"slowdownfactor"   :    3,
		"iosdelay"         :  100,
		"androiddelay"     :  0,
		"winphonedelay"    :  250,
		"fixedPixelsTop"   :    0,
		"fixedPixelsBottom":   60,
		"href" : page
	};
	
	window.plugins.nativepagetransitions.slide(
		options,
		function (msg) {console.log("success: " + msg)}, // called when the animation has finished
		function (msg) {alert("error: " + msg)} // called in case you pass in weird values
	);

**Comment by EddyVerbruggen** [comment]
Do you have the console plugin installed?

**Comment by Ibrahimwatfa** [comment]
Did not get what do you mean but for the development I'm using a normal browser so the console.log is functional.

**Comment by EddyVerbruggen** [comment]
If you are using a browser the plugin will not be available, right?

**Comment by Ibrahimwatfa** [comment]
Yes ofcourse it will not work, but on the mobile its working fine except the callback function.
Everything else is perfect.

**Comment by EddyVerbruggen** [comment]
Hence my question about the console plugin - if you're running on a device and want console messages logged (that's what's in you successcallback according to your code sample) then you need to add the [console plugin](https://github.com/apache/cordova-plugin-console). Otherwise, try use `alert`.

**Comment by Ibrahimwatfa** [comment]
I'm not saying that the console is not working, i mean that i'm not able to reach the callback function event if i used alert its not fired after the transition in complete.

That is my only concern.

Thank you for your help
Regards

**Comment by EddyVerbruggen** [comment]
OK, can you send me a sample project reproducing this issue?

**Comment by Klaster1** [comment]
To reproduce, you just need to call `plugins.nativepagetransitions.executePendingTransition(() => console.log('success'), () => console.error('error'))`. Neither of the callbacks will be called. The platform I've encountered it on is iOS 9.1, NativePageTransitions@0.5.5, Cordova iOS platform 3.9.2, com.telerik.plugins.wkwebview 0.6.7.

**Comment by EddyVerbruggen** [comment]
@Klaster1 Your issue is with `executePendingTransition` and you're right it doesn't fire the success callback. I'll look into that now.

@Ibrahimwatfa Just tested `slide` again with a delay of > 0 and it really does invoke the success callback in my app. If you want me to investigate further I need your project.

**Comment by EddyVerbruggen** [comment]
OK, the `executePendingTransition` callback has been fixed.
