### ISSUE TITLE
Plugin doesn't work with local files

### ISSUE THREAD

**Issue by tstancheva** [Telerik-Verified-Plugins/NativePageTransitions#90]
The plugin can transition to a remote page only when the page is available in the application package initially uploaded on the device. For instance in Android, the plugin seems to look for the remote views under the Android assets directory. However, if you create a new page after the app is deployed on a device and you use AppBuilder's LiveSync functionality to sync the changes, the following code will not work:
 window.plugins.nativepagetransitions.slide({
                 "href": "next.html" //next.html is created after the app is deployed and it is saved on the device through the AppBuilder LiveSync functionality
         })

This code will also not work in the AppBuilder companion apps.

**Comment by EddyVerbruggen** [comment]
Hey @tstancheva can you please give the current master branch a spin? I've tested a fix for both iOS and Android with LiveSync (debug build in AppBuilder).

**Comment by tstancheva** [comment]
It works on our side as well. Thanks for your prompt response.
