### ISSUE TITLE
slide transition - fixedPixelsTop doesn't work on iOS with up & down

### ISSUE THREAD

**Issue by trampoline** [Telerik-Verified-Plugins/NativePageTransitions#91]
i'm using 0.5.4

fixedPixelsTop works fine with left & right slide transitions, but not at all with up & down slide transitions

**Comment by EddyVerbruggen** [comment]
That's right, I didn't implement it for up and down as I didn't think it would be used. Wouldn't it look a bit silly?

**Comment by trampoline** [comment]
i think it would look ok - i wanted to use fade but #92 is stopping me using fade, so i thought to use a vertical slide for the moment, with my top-of-screen menu fixed. even without fixedPixelsTop working properly it's a lot less jarring than the #92 fade-from-black bug, and i think it would look pretty good with fixedPixelsTop

**Comment by EddyVerbruggen** [comment]
I see. Do you only need this for iOS?

**Comment by mccraigmccraig** [comment]
for the moment only iOS - i've got to make things work on android in a week or two, but i will probably take a look at seeing if i can find the bug and use fade if i can

**Comment by mccraigmccraig** [comment]
so i deployed a version of our app with up/down slides for top-level navigation and right/left for sub-nav... first two user comments are 'i like the new up/down slides' 

i'm definitely interested now to see whether they look better or worse with fixedPixelsTop... 

my instinct is that having a fixed top-menu will give the eye something to focus on while the transition happens and be more relaxing, but my instinct told me that fades were better than up/down slides for this situation, so the posterior probability of my instincts being good is falling
