### ISSUE TITLE
slide transition has stateful interaction with fade transition on iOS

### ISSUE THREAD

**Issue by trampoline** [Telerik-Verified-Plugins/NativePageTransitions#92]
i'm using 0.5.4 on iOS 9.0.2

i just switched from using a positive iosdelay to a -1 iosdelay and executePendingTransition

this works great, and has highlighted a problem with fade transition which was intermittent before i started using executePendingTransition - it now seems quite deterministic

fade transition works fine when my app starts, but after a slide transition has been executed the fade transition stops working properly - it seems to fade in to the new content from black rather than a snapshot of the old content

**Comment by EddyVerbruggen** [comment]
Interesting find, can't reproduce it though. Do you have a simple Xcode app for me to reproduce it with?

**Comment by mccraigmccraig** [comment]
i will try and extract a small test app which reproduces the problem

**Comment by EddyVerbruggen** [comment]
That would be awesome, thanks! You can mail it to eddyverbruggen at gmail.

**Comment by EddyVerbruggen** [comment]
Thanks for the project. I couldn't reproduce it at first because I was running the project in the Simulator. In my case the problem only popped up on a real device.

I have now released 0.5.5 which allows fixedPixelsTop/Bottom for slide up/down AND fixes the black fade issue.

**Comment by mccraigmccraig** [comment]
awesome :)

are changes def deployed to 0.5.5 ? i updated my plugin, but am still seeing the problems

**Comment by EddyVerbruggen** [comment]
Yeah should be - I tested with your demo app...

**Comment by mccraigmccraig** [comment]
guess i didn't clean hard enough before rebuilding :) 

all working now !

thank you :D

**Comment by EddyVerbruggen** [comment]
Awesome! :beers:
