### ISSUE TITLE
Transitions don't work with Kendo UI Application's navigate() method

### ISSUE THREAD

**Issue by TsvetinaIvanova** [Telerik-Verified-Plugins/NativePageTransitions#99]
When you use the Kendo adapter for this plugin, transitions work only when navigation is done via links. If you call the kendo.mobile.Application's navigate event, the plugin/adaptor can't capture the location change and no native transition is shown.

**Comment by EddyVerbruggen** [comment]
Hi, I did my best to enhance the adapter to hijack `app.navigate` events and reroute them to the plugin via the adapter. Seems to work great for `slide` and `flip`. Other transition effects will use non-native transtions as before.

Can you please give the updated version in the master repo a spin?

**Comment by TsvetinaIvanova** [comment]
This issue left my mind for quite some time.. So, I tested with kendo.mobile.application.navigate() and it still uses the Kendo UI navigation only.
I think that it would work if [**kendo.mobile.application.navigate**](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.mobile.application.js#L137) is successfully overwritten.

**Comment by JoeMeeks** [comment]
@EddyVerbruggen this works well for local views by id but not with remote views.
The implementation to support them on lines 67 & 159 do not work. I added this logic to line 104 and now it works. Creating PR in the adapters repo.

**Comment by JoeMeeks** [comment]
@EddyVerbruggen I should clarify, the addition to line 104 now adds support for programmatic navigation such as: 
`app.navigate('components/settings/settings.html', 'flip:right');`
Which would navigate to that view but outside of the mobile app context and thus the WKWebView would crash and reload index.html when cordova.js is not found on the remote view.

If a developer were to write all programmatic navigation with the hash prefix it would work, but now after my PR it essentially does this:
`app.navigate('#components/settings/settings.html', 'flip:right');`

**Comment by EddyVerbruggen** [comment]
Thank you @JoeMeeks, closed for now, after merging #144
